// Konspekt of the group call 2026-09-14. Generated by the call pipeline from
// GSD-BRAND/clients/sasha/sozvony/2026-09-14/KONSPEKT.html

export const SOZVON_2026_09_14 = String.raw`<!DOCTYPE html>
<html lang="ru">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Групповой созвон 14.09.2026</title>
<style>
  :root{
    --bg:#f6f3ee; --card:#fffdfa; --ink:#22201c; --muted:#87826f;
    --line:#e6e0d5; --accent:#b5763a; --accent-soft:#f0e4d4; --chip:#ece3d3;
    --quote:#6d5a33; --quote-bg:#f3ead9; --mark:#c8452f;
    --good:#3f7d4e; --good-bg:#e7f1e6; --bad:#c8452f; --bad-bg:#fbe8e3;
  }
  @media (prefers-color-scheme: dark){
    :root{
      --bg:#161411; --card:#201d18; --ink:#ece7dd; --muted:#9a9282;
      --line:#332e26; --accent:#d69a5f; --accent-soft:#33291d; --chip:#2c2519;
      --quote:#d8b483; --quote-bg:#26200f; --mark:#e8735c;
      --good:#7ec08c; --good-bg:#1c2a1e; --bad:#e8735c; --bad-bg:#2e1a15;
    }
  }
  :root[data-theme="dark"]{
    --bg:#161411; --card:#201d18; --ink:#ece7dd; --muted:#9a9282;
    --line:#332e26; --accent:#d69a5f; --accent-soft:#33291d; --chip:#2c2519;
    --quote:#d8b483; --quote-bg:#26200f; --mark:#e8735c;
    --good:#7ec08c; --good-bg:#1c2a1e; --bad:#e8735c; --bad-bg:#2e1a15;
  }
  :root[data-theme="light"]{
    --bg:#f6f3ee; --card:#fffdfa; --ink:#22201c; --muted:#87826f;
    --line:#e6e0d5; --accent:#b5763a; --accent-soft:#f0e4d4; --chip:#ece3d3;
    --quote:#6d5a33; --quote-bg:#f3ead9; --mark:#c8452f;
    --good:#3f7d4e; --good-bg:#e7f1e6; --bad:#c8452f; --bad-bg:#fbe8e3;
  }
  *{box-sizing:border-box}
  body{margin:0; background:var(--bg); color:var(--ink);
    font-family:ui-sans-serif,system-ui,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;
    line-height:1.62; font-size:17px; -webkit-font-smoothing:antialiased}
  .wrap{max-width:860px; margin:0 auto; padding:56px 24px 110px}

  header.doc{border-bottom:2px solid var(--line); padding-bottom:26px; margin-bottom:20px}
  .kicker{text-transform:uppercase; letter-spacing:.16em; font-size:11.5px; color:var(--accent); font-weight:800; margin:0 0 12px}
  h1{font-size:38px; line-height:1.06; margin:0 0 12px; font-weight:800; letter-spacing:-.015em}
  .sub{color:var(--muted); font-size:15.5px; margin:0; max-width:64ch}
  .meta{display:flex; flex-wrap:wrap; gap:8px; margin-top:18px}
  .meta span{font-size:12.5px; background:var(--chip); color:var(--ink); padding:5px 11px; border-radius:999px; font-weight:600}

  nav.toc{background:var(--card); border:1px solid var(--line); border-radius:16px; padding:20px 24px; margin:18px 0 30px}
  nav.toc h3{margin:0 0 10px; font-size:13px; text-transform:uppercase; letter-spacing:.12em; color:var(--muted)}
  nav.toc ol{margin:0; padding-left:20px; columns:2; column-gap:28px}
  nav.toc li{margin:3px 0; font-size:14px}
  nav.toc a{color:var(--ink); text-decoration:none; border-bottom:1px solid transparent}
  nav.toc a:hover{border-bottom-color:var(--accent); color:var(--accent)}
  @media (max-width:640px){ nav.toc ol{columns:1} }

  .call{margin:42px 0 8px; padding:18px 22px; background:var(--accent-soft); border-radius:14px; border:1px solid var(--line)}
  .call h2{margin:0 0 4px; font-size:24px; font-weight:800; letter-spacing:-.01em}
  .call p{margin:0; font-size:13.5px; color:var(--muted); font-weight:600}

  section{background:var(--card); border:1px solid var(--line); border-radius:16px; padding:24px 28px; margin:16px 0;
    box-shadow:0 1px 2px rgba(0,0,0,.03)}
  .sec-head{display:flex; align-items:baseline; gap:12px; margin:0 0 6px; flex-wrap:wrap}
  .sec-num{font-size:12.5px; font-weight:800; color:var(--accent); font-variant-numeric:tabular-nums; letter-spacing:.04em}
  h3.t{font-size:21px; margin:0; font-weight:800; letter-spacing:-.01em; flex:1 1 auto}
  .ts{font-size:12px; color:var(--muted); font-variant-numeric:tabular-nums; font-weight:700; background:var(--chip); padding:3px 9px; border-radius:999px}
  section > p{margin:12px 0}
  section p:first-of-type{margin-top:14px}

  section.err{border-left:4px solid var(--bad)}
  section.err .sec-num{color:var(--bad)}
  .verdict{display:inline-block; font-size:11.5px; font-weight:800; letter-spacing:.1em; text-transform:uppercase;
    padding:3px 10px; border-radius:999px}
  .verdict.good{background:var(--good-bg); color:var(--good)}
  .verdict.bad{background:var(--bad-bg); color:var(--bad)}

  ul.b{margin:12px 0; padding:0; list-style:none}
  ul.b > li{position:relative; padding:7px 0 7px 24px; border-bottom:1px dashed var(--line)}
  ul.b > li:last-child{border-bottom:none}
  ul.b > li::before{content:"›"; position:absolute; left:3px; top:7px; color:var(--accent); font-weight:800}
  b{font-weight:700}
  .q{background:var(--quote-bg); color:var(--quote); padding:2px 7px; border-radius:5px; font-style:italic}

  blockquote{margin:16px 0; padding:14px 18px; background:var(--quote-bg); border-left:3px solid var(--accent);
    border-radius:0 10px 10px 0; color:var(--quote); font-size:16px}
  blockquote p{margin:0}
  blockquote p + p{margin-top:8px}

  .box{border:1px solid var(--line); border-radius:12px; padding:16px 18px; margin:16px 0; background:var(--bg)}
  .box .lbl{font-size:11.5px; text-transform:uppercase; letter-spacing:.13em; font-weight:800; color:var(--accent); margin:0 0 8px}
  .box ol{margin:0; padding-left:20px}
  .box ol li{margin:6px 0}
  .box ul{margin:0; padding-left:20px}
  .box ul li{margin:5px 0}
  .box.fix{border-color:var(--good); background:var(--good-bg)}
  .box.fix .lbl{color:var(--good)}

  table{width:100%; border-collapse:collapse; margin:16px 0; font-size:15px}
  th,td{text-align:left; padding:9px 10px; border-bottom:1px solid var(--line); vertical-align:top}
  th{font-size:12px; text-transform:uppercase; letter-spacing:.09em; color:var(--muted)}
  td.tc{font-variant-numeric:tabular-nums; font-weight:700; color:var(--accent); white-space:nowrap}
  .scroll{overflow-x:auto}

  .steps{counter-reset:st; margin:16px 0; padding:0; list-style:none}
  .steps li{counter-increment:st; position:relative; padding:10px 0 10px 44px; border-bottom:1px solid var(--line)}
  .steps li:last-child{border-bottom:none}
  .steps li::before{content:counter(st); position:absolute; left:0; top:9px; width:28px; height:28px; border-radius:50%;
    background:var(--accent); color:#fff; font-size:13px; font-weight:800; display:flex; align-items:center; justify-content:center}

  .chk{margin:16px 0; padding:0; list-style:none}
  .chk li{position:relative; padding:9px 0 9px 30px; border-bottom:1px dashed var(--line)}
  .chk li:last-child{border-bottom:none}
  .chk li::before{content:"${'\\'}2610"; position:absolute; left:4px; top:8px; color:var(--accent); font-weight:800; font-size:16px}

  .facts{display:grid; grid-template-columns:repeat(auto-fit,minmax(150px,1fr)); gap:12px; margin:18px 0}
  .fact{background:var(--bg); border:1px solid var(--line); border-radius:12px; padding:14px 16px}
  .fact .n{font-size:26px; font-weight:800; letter-spacing:-.02em; color:var(--accent); line-height:1.1}
  .fact .l{font-size:12.5px; color:var(--muted); margin-top:4px; line-height:1.35}

  .note{font-size:13.5px; color:var(--muted); font-style:italic}
  .foot{margin-top:48px; padding-top:22px; border-top:1px solid var(--line); font-size:13px; color:var(--muted)}
  @media (max-width:560px){ .wrap{padding:36px 15px 70px} h1{font-size:29px} section{padding:20px 18px} body{font-size:16.5px} }
</style>
</head>
<body>
<div class="wrap">

  <header class="doc">
    <p class="kicker">Групповой созвон · 14 сентября 2026</p>
    <h1>Одну карусель я взял у коллеги и выложил четыре раза</h1>
    <p class="sub">Разбор по кругу: Ирина, Сева. Почему без новых людей не работает ни один оффер и ни один призыв. Зачем брать заходы, которые уже залетели, если кажется, что копировать нельзя. И как узкую нишу кондитерки выводить в широту через конфликт. Ниже вся встреча по таймкодам записи.</p>
    <div class="meta">
      <span>14.09.2026</span><span>51 мин</span><span>Ирина</span><span>Сева</span>
    </div>
  </header>

  <!--VIDEO_SLOT-->

  <nav class="toc">
    <h3>Содержание</h3>
    <ol>
      <li><a href="#glavnoe">Главное за встречу</a></li>
      <li><a href="#claude">Claude через МТС Pay: оффер превращается в презентацию</a></li>
      <li><a href="#irina">Ирина: посты в Телегу и Макс, а новых людей там нет</a></li>
      <li><a href="#shestsot">Шестьсот подписчиков это преимущество, а не беда</a></li>
      <li><a href="#karma">«Мне совесть не позволяет копировать»</a></li>
      <li><a href="#urovni">Уровни духовного пробуждения: формат, которого в СНГ ещё не видели</a></li>
      <li><a href="#princip">Сначала принцип, а не цифра подписчиков</a></li>
      <li><a href="#bog">А люди хотят довериться Богу?</a></li>
      <li><a href="#tishina">В Instagram заходят не просветиться, а заполнить паузу</a></li>
      <li><a href="#seva">Сева: контент для Кати собираем как блок для обучения</a></li>
      <li><a href="#konflikt">Как узкую кондитерку вывести в широту: через конфликт</a></li>
      <li><a href="#razbor">Разбор переписки и стейдж-созвон с комментариями Кати</a></li>
      <li><a href="#kazino">«Мы находимся в сраном казино»</a></li>
      <li><a href="#prodayushee">Продающее прячется внутри разбора</a></li>
      <li><a href="#zadachi">Задачи участникам</a></li>
      <li><a href="#citaty">Цитаты под контент</a></li>
    </ol>
  </nav>

  <div class="call"><h2>Главное</h2><p>три вещи, ради которых стоит пересмотреть запись</p></div>

  <section id="glavnoe">
    <div class="sec-head"><span class="sec-num">01</span><h3 class="t">Главное за встречу</h3></div>
    <ul class="b">
      <li><b>Без новых людей всё остальное не имеет значения.</b> Ирина месяц писала посты, офферы и призывы в Телеграм и Макс. В Телеграме у неё пятьдесят пять подписчиков, в Максе сорок пять. Новой аудитории там нет, значит и платить некому. Разбираться нужно только с Instagram.</li>
      <li><b>Оригинальность в начале ролика не нужна, нужен заход, который уже сработал.</b> Ирина не копирует из принципа и придумывает заголовки сама. Саша карусель «Публикуйте все подряд» взял у коллеги и выложил четыре раза, каждый раз собирая просмотры, аудиторию и лайки. Внутри свои смыслы, снаружи проверенный формат.</li>
      <li><b>Свои смыслы надо заворачивать в то, что хотят люди.</b> «Довериться Богу» это то, что нужно эксперту, а не зрителю. В рилсы заходят не учиться и не просветляться, а отвлечься от проблем и заполнить паузу.</li>
      <li><b>Узкую нишу в широту выводит конфликт.</b> По проекту Кати придумали два формата: разбор переписки кондитера с клиентом и стейдж-созвон с её комментариями. Разбор профилей на грин скрине уже пробовали, он работал плохо: конфликта нет, один визуальный шум.</li>
    </ul>
  </section>

  <div class="call"><h2>Перед разбором</h2><p>как купить Claude и собрать из оффера презентацию</p></div>

  <section id="claude">
    <div class="sec-head"><span class="sec-num">02</span><h3 class="t">Claude через МТС Pay: оффер превращается в презентацию</h3><span class="ts">00:00 · 04:12</span></div>
    <p>Claude в России недоступен, но его можно взять через МТС Pay. На сайте МТС есть раздел зарубежных сервисов, внутри нейросети, там Claude. Цену уже подняли: две шестьсот восемьдесят пять. <span class="q">Но, ребят, это стоит своих денег.</span></p>
    <div class="box">
      <p class="lbl">Что Саша показал на живом примере</p>
      <p>Взял оффер, который участник прислал в общий чат, вставил текст без всякого контекста и написал: <span class="q">преврати мне этот оффер в презентацию для музыканта и сделай это в максимально дорогой стилистике</span>.</p>
      <p>Так же собираются карусели, презентации и сайты. Работает и через приложение.</p>
    </div>
  </section>

  <div class="call"><h2>По кругу</h2><p>разбор каждого участника</p></div>

  <section id="irina">
    <div class="sec-head"><span class="sec-num">03</span><h3 class="t">Ирина: посты в Телегу и Макс, а новых людей там нет</h3><span class="ts">04:25 · 06:34</span></div>
    <p>Первая фраза Ирины про месяц: <span class="q">я экспериментирую, и у меня ничего не получается</span>. По деньгам: <span class="q">за тот месяц почти десять тысяч, а за этот уже вообще ноль пять</span>.</p>
    <p>Действия за месяц она перечисляет: посты в Instagram, в Telegram, в Макс, постоянные призывы, офферы в Телеграме. Любую жизненную тему берёт и пропускает через себя.</p>
    <p>Дальше один вопрос про подписчиков. <span class="q">В Телеграме у меня пятьдесят пять, в Макс сорок пять.</span></p>
    <div class="box fix">
      <p class="lbl">Почему это не даёт продаж</p>
      <p>Нету смысла направлять фокус туда, где нет новых людей. Они не будут платить деньги. <span class="q">Без новых людей вообще всё остальное не имеет значения.</span></p>
      <p>Значит разбираться нужно ровно с одним: с Instagram и с тем, что мешает приходить новым людям.</p>
    </div>
    <p class="note">Ирина про Instagram: <span class="q">это вообще боль всей моей жизни</span>. Саша просит ссылку и открывает профиль прямо на созвоне.</p>
  </section>

  <section id="shestsot">
    <div class="sec-head"><span class="sec-num">04</span><h3 class="t">Шестьсот подписчиков это преимущество, а не беда</h3><span class="ts">07:08 · 08:07</span></div>
    <p>Ирина рассказывает, что у неё было три с половиной тысячи подписчиков. <span class="q">Я их почистила с психу. Сейчас у меня вообще шестьсот семьдесят шесть, и я жалею.</span> И добавляет: <span class="q">три пятьсот выглядело намного интереснее</span>.</p>
    <p>Ответ: цифра могла мешать сильнее. <span class="q">Людей, у которых есть аудитория, к ним больше требований по контенту.</span></p>
    <div class="box">
      <p class="lbl">Логика, которую Ирина сама вспомнила</p>
      <p>Аккаунту с шестьюстами подписчиками, чтобы сделать ролик на пятьдесят тысяч просмотров, нужно в пятьдесят раз меньше, чем аккаунту с набранной аудиторией. Там к тебе уже есть ожидания, и просто так выложить не получится.</p>
    </div>
    <p class="note">Отдельно про качели: новый аккаунт она создавала и удалила, тоже с психу. <span class="q">Вообще у меня такие качели, но новые очень сложно вести.</span></p>
  </section>

  <section id="karma">
    <div class="sec-head"><span class="sec-num">05</span><h3 class="t">«Мне совесть не позволяет копировать»</h3><span class="ts">08:31 · 11:20</span></div>
    <p>Вопрос был простой: делала ли она хоть что-то из того, что у коллег уже залетало. Ирина отвечает, что много наблюдает, но берёт не один в один.</p>
    <p><span class="q">Я как бы карма, все дела, я таким не занимаюсь, я всё через себя, всё меняю, под себя настраиваю.</span> И дальше прямее: <span class="q">я же не могу, мне как бы совесть не позволяет копировать</span>.</p>
    <div class="box fix">
      <p class="lbl">Разбор на своём примере</p>
      <p><span class="q">Карма это прекрасно. А мы хотим, чтобы это работало или хотим дальше через себя это всё пропускать?</span></p>
      <p>Карусель «Публикуйте все подряд» Саша взял у коллеги. Название чужое, смыслы внутри каждый раз новые. Выложил её четыре раза, и все четыре раза она набирала просмотры, аудиторию и лайки.</p>
      <p>Вопрос Ирине: я копирую или нет? Её ответ: копируешь, просто добавляешь своё.</p>
    </div>
    <p class="note">После этого Ирина переформулировала свою же практику: <span class="q">я беру то, что у людей сработало, и чуть-чуть меняю, чтобы не было плагиата</span>. Разница именно в том, насколько меняешь начало.</p>
  </section>

  <section id="urovni">
    <div class="sec-head"><span class="sec-num">06</span><h3 class="t">Уровни духовного пробуждения: формат, которого в СНГ ещё не видели</h3><span class="ts">12:03 · 14:57</span></div>
    <p>Ирина называет свой референс: диалоги со Вселенной, когда человек обращается, а Вселенная отвечает. Здесь важная поправка по технике.</p>
    <p><span class="q">Там первые три-четыре секунды очень важно, чтобы похожи, одинаковыми были.</span> Если брать только общую идею диалога, ролик может и не сработать.</p>
    <p>Сама Ирина замечает, что таких блогеров стало очень много. <span class="q">Первые ребята собрали сливки, кто начал это копировать. И сейчас уже, если все это делают, это снова перестаёт работать.</span></p>
    <div class="box">
      <p class="lbl">Формат, который Саша показал на экране · 12:44</p>
      <p>Зарубежный автор из духовных практик. Три уровня: новичок, любитель, продвинутый. Сверху тезис, например создание собственной реальности. Дальше по очереди: как об этом думает новичок, как любитель, как продвинутый.</p>
      <p>В СНГ Саша такого ещё не видел. Задача Ирине: собрать то же самое на своей теме.</p>
    </div>
    <p class="note">На возражение «я английский не знаю» ответ короткий: неважно, речь про формат, а не про язык.</p>
  </section>

  <section id="princip">
    <div class="sec-head"><span class="sec-num">07</span><h3 class="t">Сначала принцип, а не цифра подписчиков</h3><span class="ts">14:57 · 16:39</span></div>
    <p><span class="q">Себе важно разобраться с притоком нового трафика. Пока этого не будет, всё остальное не имеет смысла.</span></p>
    <p>Ирина переспрашивает: то есть сначала набрать аудиторию, а потом снимать? Нет. Смысл не в цифре, а в том, чтобы понять принцип и чтобы ролики начали набирать выше среднего: полторы, две, три, пять, шесть, десять тысяч. Когда пойдёт хоть какой-то поток, можно возобновлять продажи.</p>
    <p class="note">Попутно про её нынешние форматы: <span class="q">сценки уже тоже не работают, они работали года два-три назад</span>. Это не про отсутствие индивидуальности, это про срок жизни формата.</p>
  </section>

  <section id="bog">
    <div class="sec-head"><span class="sec-num">08</span><h3 class="t">А люди хотят довериться Богу?</h3><span class="ts">16:39 · 19:22</span></div>
    <p>Ирина сама выбирает ролик, который считает целиком своим: про довериться Богу. Заголовок придумала сама.</p>
    <p><span class="q">А люди хотят довериться Богу?</span> Вопрос не про индивидуальность и не про правильность. Вопрос один: <span class="q">когда человек заходит в Instagram, какую выгоду он получит, просмотрев это видео?</span></p>
    <p>Ирина возражает, что такая аудитория есть, просто она у других блогеров. Ответ на это: <span class="q">а как они её набрали? Они набрали её, потому что говорили: смотрите, как довериться Богу.</span></p>
    <div class="box fix">
      <p class="lbl">Что делать с заголовками</p>
      <p>Сначала брать заходы и темы, которые уже залетели. Смотреть на YouTube и в Threads. Говорить при этом можно абсолютно всё то же самое, свои идеи никто не отменяет. Начинаться должно с тезиса, который людям любопытен.</p>
    </div>
    <p class="note">На слово «хук» реакция отдельная: <span class="q">хук это уже как слово проститутка</span>. Дело не в термине, а в том, попадает начало в чужой интерес или нет.</p>
  </section>

  <section id="tishina">
    <div class="sec-head"><span class="sec-num">09</span><h3 class="t">В Instagram заходят не просветиться, а заполнить паузу</h3><span class="ts">19:22 · 22:43</span></div>
    <p><span class="q">То, что ты хочешь сказать, и те смыслы, которые ты хочешь транслировать, тебе важно заворачивать в то, что хотят люди.</span> Пока это её собственная оценка того, что людям надо.</p>
    <p><span class="q">Люди заходят в соцсети, в Instagram, смотрят рилсы уж точно не для того, чтобы чему-то научиться или просветиться. Они смотрят для того, чтобы наоборот отвлечься от своих проблем, заполнить паузу, не сталкиваться с тишиной.</span></p>
    <p>Ирина спрашивает, как серьёзные темы завернуть в формат отдыха. Ответ обратным вопросом: <span class="q">а Бог не отдыхает? Мы же говорим про довериться Богу. Может быть, в этом и есть отдых.</span></p>
    <div class="box">
      <p class="lbl">Про честность в цифрах</p>
      <p>Это в любом случае рулетка. <span class="q">Можно и триста рилсов снять, стреляя наугад.</span> Но <span class="q">важно совершать какие-то действия, которые повышают шансы на то, чтобы это сработало</span>.</p>
    </div>
    <div class="box fix">
      <p class="lbl">Где искать в кабинете · 30:29</p>
      <p>Ирина не нашла раздел, разбирались прямо на созвоне. Заходишь в бота, в мини-приложение, ниже «Новый уровень контента», внутри видеоуроки по шести уровням. В самом низу практикум «Три способа найти упаковку», там уровень пять: теория и практика.</p>
      <p>Отдельно запись прошлого понедельника с Севой: сорок минут живого написания сценария, там принцип упаковки показан целиком. Посмотреть желательно в тот же день.</p>
    </div>
    <p class="note">Итог от Ирины короткий: чуть яснее стало.</p>
  </section>

  <section id="seva">
    <div class="sec-head"><span class="sec-num">10</span><h3 class="t">Сева: контент для Кати собираем как блок для обучения</h3><span class="ts">22:45 · 25:55</span></div>
    <p>Вторая половина встречи это рабочая сессия с Севой по проекту Кати. Отдельный созвон на сборку контента назначили на завтра.</p>
    <p>Предложение Севы: записать эту сборку как блок и потом использовать в обучении. <span class="q">Просто может получиться очень сильно классно, может, просто классно.</span></p>
    <p class="note">Материал для работы уже собран: анкеты, которые заполняли люди Кати, её Телеграм, её Инстаграм и тонна её голосовых. Всего, что нужно для приемлемого результата, достаточно.</p>
  </section>

  <section id="konflikt">
    <div class="sec-head"><span class="sec-num">11</span><h3 class="t">Как узкую кондитерку вывести в широту: через конфликт</h3><span class="ts">25:55 · 30:20</span></div>
    <p>Вопрос, с которого начался разбор: у Кати достаточно узкая ниша, кондитерка, как её выводить в широту. Ответ Севы сразу: через конфликт в переписке с клиентом или на созвоне.</p>
    <p>Дальше пошли примеры, как это может звучать в ролике: <span class="q">где, где мой торт, сука?</span>, <span class="q">почему вы мне привезли торт с хуями?</span>, <span class="q">я заказала торт на годовщину с мужем, и мы развелись. Мы из-за торта развелись.</span></p>
    <div class="box">
      <p class="lbl">Почему такие ролики залетают</p>
      <p>У Саши знакомый делал ролики с переписками, когда работал с компанией по клубнике, и они заходили. Механика проверенная, вопрос только в том, кто внутри неё говорит.</p>
    </div>
    <p>Развилка: Катя не кондитер, она помогает кондитерам продвигаться в онлайне. Кондитером она была раньше и быстро поняла, что денег будет сильно больше, если помогать другим. Значит в ролике она не отвечает клиенту, а разбирает, как отвечает кондитер.</p>
    <p class="note">Идея Севы про разбор разбора: он видел ролик, где рилс-продюсер с каменным лицом смотрит сторителлинг предпринимателя, ставит на паузу и комментирует. А это сам был разбор разбора, снятый другим рилс-продюсером.</p>
  </section>

  <section id="razbor">
    <div class="sec-head"><span class="sec-num">12</span><h3 class="t">Разбор переписки и стейдж-созвон с комментариями Кати</h3><span class="ts">30:20 · 34:03</span></div>
    <p>Собрались два формата на тест:</p>
    <ul class="b">
      <li>Видос с перепиской кондитера и клиента, который Катя комментирует.</li>
      <li>Стейдж-созвон: прописывается сценарий созвона и отдельно комментарии Кати к нему. По сути двойной сценарий.</li>
    </ul>
    <p>Про лица решили сразу: без лиц. <span class="q">С лицами это, конечно, хардкор. Это актёры нужны. Это слишком сложно с точки зрения воспроизведения будет.</span></p>
    <p class="note">Договорённость по объёму: первые два таких формата, на тест этого хватит. Новые форматы не выдумывать, пока эти не отработали.</p>
  </section>

  <section id="kazino">
    <div class="sec-head"><span class="sec-num">13</span><h3 class="t">«Мы находимся в сраном казино»</h3><span class="ts">34:03 · 36:27</span></div>
    <p>Дальше про то, как ставить это на поток. Два креативных формата нужны, чтобы показать Кате саму возможность, плюс рекомендации, как ей эти гипотезы тестить.</p>
    <p><span class="q">Мы находимся в сраном казино.</span> Одна идея, загруженная один раз, может не сработать из-за миллиона причин и факторов. Поэтому вариативность закладывается сразу: три-четыре ролика, которые можно выложить в разрезе одного дня.</p>
    <div class="box fix">
      <p class="lbl">Два типа роликов в одном месяце</p>
      <p>Есть ролики на широкий захват внимания. И есть продающие, потому что у Кати всё завязано на продаже. Нужно жонглирование между ними, а не только креатив.</p>
      <p>Считать удобнее универсально: четыре формата за месяц, два креативных и два продающих.</p>
    </div>
  </section>

  <section id="prodayushee">
    <div class="sec-head"><span class="sec-num">14</span><h3 class="t">Продающее прячется внутри разбора</h3><span class="ts">36:31 · 38:47</span></div>
    <p>Сева возвращается к недосказанной мысли: формат с разбором сам по себе может быть продающим. <span class="q">Она будет отрабатывать, и она будет говорить: а вот здесь вам нужно было сделать вот так. То есть она свою экспертность будет продавать в этом формате.</span></p>
    <p>Уточнение от Саши: Катя работает не столько с продажами напрямую, сколько с Инстаграмами кондитеров, помогает упаковать профиль так, чтобы его было интересно смотреть и чтобы он продавал.</p>
    <div class="box">
      <p class="lbl">Что уже пробовали и что не пошло</p>
      <p>Разбор страничек Инстаграма работал плохо. Причина: <span class="q">конфликта как такового нету, там это визуальный шум, когда ты профиль загружаешь и поверх него на грин скрине что-то ебашишь</span>.</p>
      <p>Значит в кадре должен быть процесс продажи: обсуждение, коммуникация с клиентом. Чтобы был конфликт.</p>
    </div>
    <p class="note">Вариант монтажа от Севы: если конфликт сам по себе интересный, Катя может просто тридцать секунд смотреть и кивать головой, а в конце убрать телефон и дать call to action. Не обязательно пинг-понг.</p>
  </section>

  <div class="call"><h2>Дальше</h2><p>что каждый делает до следующей встречи</p></div>

  <section id="zadachi">
    <div class="sec-head"><span class="sec-num">15</span><h3 class="t">Задачи участникам</h3></div>
    <ul class="b">
      <li><b>Ирина.</b> Фокус только на Instagram, в Телеграме и Максе новых людей нет. Посмотреть практикум «Три способа найти упаковку» в разделе «Новый уровень контента», уровень пять: теория и практика, желательно в тот же день. Пересмотреть блоки про поток спроса и про то, как заворачивать свои смыслы в то, что хотят люди. Брать заходы и темы, которые уже залетели, смотреть YouTube и Threads, повторять первые три-четыре секунды. Попробовать формат «уровни духовного пробуждения»: как об одном тезисе думает новичок, любитель и профи. Саша напишет чуть позже.</li>
      <li><b>Сева.</b> Созвон завтра в 16:00 по Москве, собирать контент по Кате. Прописать два креативных формата: разбор переписки с комментариями и стейдж-созвон, оба без лиц. Плюс пара продающих рилсов. Рилсы на Севе, карусели на Саше. Эту сборку записать как блок для обучения.</li>
    </ul>
  </section>

  <section id="citaty">
    <div class="sec-head"><span class="sec-num">16</span><h3 class="t">Цитаты под контент</h3></div>
    <ul class="b">
      <li>Без новых людей вообще всё остальное не имеет значения.</li>
      <li>Людей, у которых есть аудитория, к ним больше требований по контенту.</li>
      <li>Карма это прекрасно. А мы хотим, чтобы это работало или хотим дальше через себя это всё пропускать?</li>
      <li>Первые ребята собрали сливки. И сейчас уже, если все это делают, это снова перестаёт работать.</li>
      <li>Там первые три-четыре секунды очень важно, чтобы одинаковыми были.</li>
      <li>Люди смотрят рилсы уж точно не для того, чтобы чему-то научиться или просветиться. Они смотрят, чтобы отвлечься от своих проблем, заполнить паузу, не сталкиваться с тишиной.</li>
      <li>А Бог не отдыхает?</li>
      <li>Можно и триста рилсов снять, стреляя наугад. Это просто рулетка.</li>
      <li>Мы находимся в сраном казино.</li>
    </ul>
  </section>

</div>
</body>
</html>
`;
