// Konspekt of the personal call 2026-10-06. Generated by the call pipeline.

export const LICHNOE_LICHNYY_SOZVON_RAMIL_2026_10_06 = String.raw`<!DOCTYPE html>
<html lang="ru">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Личный созвон 06.10.2026</title>
<style>
  :root{
    --bg:#f6f3ee; --card:#fffdfa; --ink:#22201c; --muted:#87826f;
    --line:#e6e0d5; --accent:#b5763a; --accent-soft:#f0e4d4; --chip:#ece3d3;
    --quote:#6d5a33; --quote-bg:#f3ead9; --mark:#c8452f;
    --good:#3f7d4e; --good-bg:#e7f1e6; --bad:#c8452f; --bad-bg:#fbe8e3;
  }
  @media (prefers-color-scheme: dark){
    :root{
      --bg:#161411; --card:#201d18; --ink:#ece7dd; --muted:#9a9282;
      --line:#332e26; --accent:#d69a5f; --accent-soft:#33291d; --chip:#2c2519;
      --quote:#d8b483; --quote-bg:#26200f; --mark:#e8735c;
      --good:#7ec08c; --good-bg:#1c2a1e; --bad:#e8735c; --bad-bg:#2e1a15;
    }
  }
  :root[data-theme="dark"]{
    --bg:#161411; --card:#201d18; --ink:#ece7dd; --muted:#9a9282;
    --line:#332e26; --accent:#d69a5f; --accent-soft:#33291d; --chip:#2c2519;
    --quote:#d8b483; --quote-bg:#26200f; --mark:#e8735c;
    --good:#7ec08c; --good-bg:#1c2a1e; --bad:#e8735c; --bad-bg:#2e1a15;
  }
  :root[data-theme="light"]{
    --bg:#f6f3ee; --card:#fffdfa; --ink:#22201c; --muted:#87826f;
    --line:#e6e0d5; --accent:#b5763a; --accent-soft:#f0e4d4; --chip:#ece3d3;
    --quote:#6d5a33; --quote-bg:#f3ead9; --mark:#c8452f;
    --good:#3f7d4e; --good-bg:#e7f1e6; --bad:#c8452f; --bad-bg:#fbe8e3;
  }
  *{box-sizing:border-box}
  body{margin:0; background:var(--bg); color:var(--ink);
    font-family:ui-sans-serif,system-ui,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;
    line-height:1.62; font-size:17px; -webkit-font-smoothing:antialiased}
  .wrap{max-width:860px; margin:0 auto; padding:56px 24px 110px}

  header.doc{border-bottom:2px solid var(--line); padding-bottom:26px; margin-bottom:20px}
  .kicker{text-transform:uppercase; letter-spacing:.16em; font-size:11.5px; color:var(--accent); font-weight:800; margin:0 0 12px}
  h1{font-size:38px; line-height:1.06; margin:0 0 12px; font-weight:800; letter-spacing:-.015em}
  .sub{color:var(--muted); font-size:15.5px; margin:0; max-width:64ch}
  .meta{display:flex; flex-wrap:wrap; gap:8px; margin-top:18px}
  .meta span{font-size:12.5px; background:var(--chip); color:var(--ink); padding:5px 11px; border-radius:999px; font-weight:600}

  nav.toc{background:var(--card); border:1px solid var(--line); border-radius:16px; padding:20px 24px; margin:18px 0 30px}
  nav.toc h3{margin:0 0 10px; font-size:13px; text-transform:uppercase; letter-spacing:.12em; color:var(--muted)}
  nav.toc ol{margin:0; padding-left:20px; columns:2; column-gap:28px}
  nav.toc li{margin:3px 0; font-size:14px}
  nav.toc a{color:var(--ink); text-decoration:none; border-bottom:1px solid transparent}
  nav.toc a:hover{border-bottom-color:var(--accent); color:var(--accent)}
  @media (max-width:640px){ nav.toc ol{columns:1} }

  .call{margin:42px 0 8px; padding:18px 22px; background:var(--accent-soft); border-radius:14px; border:1px solid var(--line)}
  .call h2{margin:0 0 4px; font-size:24px; font-weight:800; letter-spacing:-.01em}
  .call p{margin:0; font-size:13.5px; color:var(--muted); font-weight:600}

  section{background:var(--card); border:1px solid var(--line); border-radius:16px; padding:24px 28px; margin:16px 0;
    box-shadow:0 1px 2px rgba(0,0,0,.03)}
  .sec-head{display:flex; align-items:baseline; gap:12px; margin:0 0 6px; flex-wrap:wrap}
  .sec-num{font-size:12.5px; font-weight:800; color:var(--accent); font-variant-numeric:tabular-nums; letter-spacing:.04em}
  h3.t{font-size:21px; margin:0; font-weight:800; letter-spacing:-.01em; flex:1 1 auto}
  .ts{font-size:12px; color:var(--muted); font-variant-numeric:tabular-nums; font-weight:700; background:var(--chip); padding:3px 9px; border-radius:999px}
  section > p{margin:12px 0}
  section p:first-of-type{margin-top:14px}

  section.err{border-left:4px solid var(--bad)}
  section.err .sec-num{color:var(--bad)}
  .verdict{display:inline-block; font-size:11.5px; font-weight:800; letter-spacing:.1em; text-transform:uppercase;
    padding:3px 10px; border-radius:999px}
  .verdict.good{background:var(--good-bg); color:var(--good)}
  .verdict.bad{background:var(--bad-bg); color:var(--bad)}

  ul.b{margin:12px 0; padding:0; list-style:none}
  ul.b > li{position:relative; padding:7px 0 7px 24px; border-bottom:1px dashed var(--line)}
  ul.b > li:last-child{border-bottom:none}
  ul.b > li::before{content:"›"; position:absolute; left:3px; top:7px; color:var(--accent); font-weight:800}
  b{font-weight:700}
  .q{background:var(--quote-bg); color:var(--quote); padding:2px 7px; border-radius:5px; font-style:italic}

  blockquote{margin:16px 0; padding:14px 18px; background:var(--quote-bg); border-left:3px solid var(--accent);
    border-radius:0 10px 10px 0; color:var(--quote); font-size:16px}
  blockquote p{margin:0}
  blockquote p + p{margin-top:8px}

  .box{border:1px solid var(--line); border-radius:12px; padding:16px 18px; margin:16px 0; background:var(--bg)}
  .box .lbl{font-size:11.5px; text-transform:uppercase; letter-spacing:.13em; font-weight:800; color:var(--accent); margin:0 0 8px}
  .box ol{margin:0; padding-left:20px}
  .box ol li{margin:6px 0}
  .box ul{margin:0; padding-left:20px}
  .box ul li{margin:5px 0}
  .box.fix{border-color:var(--good); background:var(--good-bg)}
  .box.fix .lbl{color:var(--good)}

  table{width:100%; border-collapse:collapse; margin:16px 0; font-size:15px}
  th,td{text-align:left; padding:9px 10px; border-bottom:1px solid var(--line); vertical-align:top}
  th{font-size:12px; text-transform:uppercase; letter-spacing:.09em; color:var(--muted)}
  td.tc{font-variant-numeric:tabular-nums; font-weight:700; color:var(--accent); white-space:nowrap}
  span.tc{font-size:12.5px; font-variant-numeric:tabular-nums; font-weight:700; color:var(--accent); background:var(--accent-soft); padding:2px 7px; border-radius:999px; margin-right:6px; white-space:nowrap}
  .scroll{overflow-x:auto}

  .steps{counter-reset:st; margin:16px 0; padding:0; list-style:none}
  .steps li{counter-increment:st; position:relative; padding:10px 0 10px 44px; border-bottom:1px solid var(--line)}
  .steps li:last-child{border-bottom:none}
  .steps li::before{content:counter(st); position:absolute; left:0; top:9px; width:28px; height:28px; border-radius:50%;
    background:var(--accent); color:#fff; font-size:13px; font-weight:800; display:flex; align-items:center; justify-content:center}

  .chk{margin:16px 0; padding:0; list-style:none}
  .chk li{position:relative; padding:9px 0 9px 30px; border-bottom:1px dashed var(--line)}
  .chk li:last-child{border-bottom:none}
  .chk li::before{content:"${'\\'}2610"; position:absolute; left:4px; top:8px; color:var(--accent); font-weight:800; font-size:16px}

  .facts{display:grid; grid-template-columns:repeat(auto-fit,minmax(150px,1fr)); gap:12px; margin:18px 0}
  .fact{background:var(--bg); border:1px solid var(--line); border-radius:12px; padding:14px 16px}
  .fact .n{font-size:26px; font-weight:800; letter-spacing:-.02em; color:var(--accent); line-height:1.1}
  .fact .l{font-size:12.5px; color:var(--muted); margin-top:4px; line-height:1.35}

  .note{font-size:13.5px; color:var(--muted); font-style:italic}
  .foot{margin-top:48px; padding-top:22px; border-top:1px solid var(--line); font-size:13px; color:var(--muted)}
  @media (max-width:560px){ .wrap{padding:36px 15px 70px} h1{font-size:29px} section{padding:20px 18px} body{font-size:16.5px} }
</style>
</head>
<body>
<div class="wrap">

<header class="doc">
  <p class="kicker">Личный созвон · 6 октября 2026</p>
  <h1>Первые страницы книги</h1>
  <p class="sub">Начали с аккаунта, который ты скинул как пример, и дошли до главного: твой метод это не психология,
  и людям, которые ищут избавление, он не адресован. Длинный оффер на сопровождение откладываем, он всегда
  персональный и звучит из твоих уст на самой сессии. Собираем оффер на вход, на две демоверсии, где человек
  пробует метод на вкус, как первые страницы книги. И делаем это на языке того, чего человек хочет, а не того, что ему надо.</p>
  <div class="meta">
    <span>20 минут</span>
  </div>
</header>

<!--VIDEO_SLOT-->

<nav class="toc">
  <h3>О чём говорили</h3>
  <ol>
    <li><a href="#s1">Аккаунт как пример</a></li>
    <li><a href="#s2">Это не психология</a></li>
    <li><a href="#s3">Ступени не делятся</a></li>
    <li><a href="#s4">Зачем тогда две демоверсии</a></li>
    <li><a href="#s5">Человек приходит со своим запросом</a></li>
    <li><a href="#s6">Две сессии как конвертер</a></li>
    <li><a href="#s7">Длинный оффер откладываем</a></li>
    <li><a href="#s8">Надо и хочу</a></li>
    <li><a href="#s9">На чём остановились</a></li>
  </ol>
</nav>

<div class="call">
  <h2>Часть 1. Метод</h2>
  <p>Что в примере подходит, а что нет</p>
</div>

<section id="s1">
  <div class="sec-head">
    <span class="sec-num">01</span>
    <h3 class="t">Аккаунт как пример</h3>
    <span class="ts">00:03:23</span>
  </div>
  <p>Ты скинул аккаунт как пример и сразу сказал, что в нём не так: <span class="q">там человек где-то спрятался
  за какими-то формулировками, его там живого нету и не присутствует</span>. С этим я согласен на сто процентов.</p>
  <p>Механика у него такая: видео через искусственный интеллект, каждое заканчивается статьёй, напиши в личку и получи
  статью. Понятно, как это работает. Но под твою историю это не ложится: ты пытаешься большее запихнуть в меньшее,
  и такой пазл не сложится.</p>
  <div class="box">
    <p class="lbl">Что берём, что нет</p>
    <ul>
      <li>Идеи, которые там транслируются, тебе близки, это плюс</li>
      <li>Человека за формулировками нет, это минус</li>
      <li>Заход через статьи под твой разговор о духовном не подходит</li>
    </ul>
  </div>
</section>

<section id="s2">
  <div class="sec-head">
    <span class="sec-num">02</span>
    <h3 class="t">Это не психология</h3>
    <span class="ts">00:07:07</span>
  </div>
  <p>Главное, что ты просил не потерять: твоя система не относится к психологизму. Ты не даёшь людям готовых решений,
  через которые они что-то получают и всё. Если педалировать систему, придут люди за избавлением от чего-то, а это не твои люди.</p>
  <blockquote><p>Мне нужны люди, которые уже опробовали этой психологии, и она у них уже поперёк горла стоит.</p></blockquote>
  <p>Отсюда и твоя осторожность с обещаниями. Чтобы продавать, обещания нужны, это понятно. Но здесь они должны быть максимально аккуратными.</p>
</section>

<section id="s3">
  <div class="sec-head">
    <span class="sec-num">03</span>
    <h3 class="t">Ступени не делятся</h3>
    <span class="ts">00:08:44</span>
  </div>
  <p>Разговор у тебя в целом идёт о духовном, а ступени это попытка сформулировать его в слова. Разделить их нельзя:
  <span class="q">это всё имеет эмерджентные свойства, это всё слито и неразделимо, в разделении это не работает</span>.
  Человек не проходит первое, чтобы потом ходить иначе.</p>
  <p>Твоя идея на этот счёт: пусть супруга сыграет роль человека, который пришёл на обучение и проходит первую ступень.
  Так первую ступень можно показать на живом примере.</p>
</section>

<section id="s4">
  <div class="sec-head">
    <span class="sec-num">04</span>
    <h3 class="t">Зачем тогда две демоверсии</h3>
    <span class="ts">00:09:21</span>
  </div>
  <p>Здесь я увидел противоречие: ты писал про две бесплатные демоверсии внутри оффера, а теперь говоришь, что делить нельзя.
  Ты развернул так: на демоверсии человек приходит, чтобы столкнуться и послушать, что ты говоришь.</p>
  <blockquote><p>Как книгу берёшь, читаешь первые какие-то страницы и понимаешь, будешь ты её дальше читать или не будешь.</p></blockquote>
  <p>При этом человек всё равно придёт со своим запросом. В глубокие истории ты на демо не лезешь, берёшь самое простое:
  ребёнок постоянно не слушается в школе, муж меня не слышит. За эти две сессии человек чувствует присоединение
  и решает, надо ему с тобой разговаривать или не надо.</p>
</section>

<div class="call">
  <h2>Часть 2. Оффер на вход</h2>
  <p>Что человек покупает до большой работы</p>
</div>

<section id="s5">
  <div class="sec-head">
    <span class="sec-num">05</span>
    <h3 class="t">Человек приходит со своим запросом</h3>
    <span class="ts">00:10:57</span>
  </div>
  <p>Эту твою мысль мы и берём за основу. На внешнем уровне мы привлекаем человека через его запросы. Если он не знает,
  что ты можешь помочь с тем, что у него болит, он просто не дойдёт ни до созвона, ни до демоверсий.</p>
  <p>Полную картину оффера и то, как ты это преподносишь на сессии, пока не трогаем. В темы и ядра контента тоже не идём,
  чтобы не обсудить всё по двадцать процентов и не сдвинуть основной рычаг. Задача одна: сделать так, чтобы человек пришёл на демо.</p>
</section>

<section id="s6">
  <div class="sec-head">
    <span class="sec-num">06</span>
    <h3 class="t">Две сессии как конвертер</h3>
    <span class="ts">00:13:15</span>
  </div>
  <p>Ты говоришь: человек придёт со своим психологизмом, чтобы решили его проблему. В этом и задача двух сессий.
  Ты разворачиваешь мышление и показываешь, что избавление от психологизма убирает последствия, а не причины.
  Дальше идут те самые инсайты, про которые ты рассказывал на прошлом созвоне, и предложение о работе становится
  логичным продолжением разговора.</p>
  <blockquote><p>Мне нужно показать человеку, что ответ внутри него. Просто показать, пойдёт он туда или не пойдёт.
  Это уже его история.</p></blockquote>
  <p>То есть две сессии работают как конвертер. У других эту роль играет статья-лид-магнит: её читают, она разворачивает
  мышление и двигает человека дальше. У тебя то же самое происходит внутри созвонов.</p>
</section>

<section id="s7">
  <div class="sec-head">
    <span class="sec-num">07</span>
    <h3 class="t">Длинный оффер откладываем</h3>
    <span class="ts">00:14:23</span>
  </div>
  <p>Универсальный оффер на три месяца работы с тобой собрать не получится. Это всегда персонализированная история,
  а <span class="q">попытка попасть во всех будет приводить к тому, что мы не будем попадать ни в кого</span>.
  Длинное сопровождение ты озвучиваешь человеку сам, на сессии, в зависимости от того пути, который вы прошли.</p>
  <p>Значит, собираем оффер на вход: что человек получит за эти две демоверсии. Названия тут важны.</p>
  <div class="box fix">
    <p class="lbl">Как будет</p>
    <ul>
      <li>Оффер на сопровождение откладываем, он звучит персонально на сессии</li>
      <li>Собираем оффер на две демоверсии</li>
      <li>Слова «диагностика», «разбор», «консультация» не используем: это работало в 2020-2022, когда разборы популяризировал Михаил Гребенюк, сейчас на такое записываются неохотно</li>
      <li>Обещаем только то, что реально можем дать</li>
    </ul>
  </div>
</section>

<section id="s8">
  <div class="sec-head">
    <span class="sec-num">08</span>
    <h3 class="t">Надо и хочу</h3>
    <span class="ts">00:16:33</span>
  </div>
  <p>Твоя первая формулировка: демоверсия, попробовать для себя на вкус полного тренинга, соприкоснуться с самим методом
  и понять, подходят ли тебе эти диалоги о духовном. Само слово «демоверсия» в эту историю ложится хорошо.</p>
  <p>Но дальше нам нужно было засинхрониться, и я сказал прямо:</p>
  <blockquote><p>То, о чём ты говоришь мне, это то, что им надо. Это не то, чего они хотят. Если мы это «надо»
  не оборачиваем в их «хочу», это будет очень тяжело, плохо и грузно работать.</p></blockquote>
  <p>Ты ответил: <span class="q">вот в этом весь и прикол этой истории, я понимаю, о чём ты говоришь</span>. На этом и остановились.</p>
</section>

<section id="s9">
  <div class="sec-head">
    <span class="sec-num">09</span>
    <h3 class="t">На чём остановились</h3>
    <span class="ts">00:17:59</span>
  </div>
  <ul class="chk">
    <li>Описать своими словами, что человек получает за две демоверсии. Не через метод, а через то, чего человек хочет</li>
    <li>Собрать список простых запросов, с которыми люди реально приходят: ребёнок не слушается в школе, муж не слышит</li>
    <li>Продумать идею с супругой: как показать первую ступень на живом примере</li>
  </ul>
  <div class="box">
    <p class="lbl">За мной</p>
    <ul>
      <li>Собрать оффер на вход, на две демоверсии, без «разборов» и «диагностик»</li>
      <li>Держать длинный оффер на паузе, пока не заработает вход</li>
      <li>Темы и ядра контента берём после оффера на вход</li>
    </ul>
  </div>
  <p>Сроков в этот раз не ставили.</p>
</section>

<div class="foot">
  Личный созвон 6 октября 2026, 20 минут.
</div>

</div>
</body>
</html>
`;
